name: Run tests

on: [push, pull_request]

jobs:  
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2

  
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.7

    - name: Run go test with coverage
      run: go test . -coverprofile cover.out

