name: Run tests

on: [push, pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.7
    
    - name: list files
      run: ls -l

    - name: Run go test with coverage
      run: go test . -coverprofile cover.out